"""initial migaration

Revision ID: 22ff49eefe23
Revises: 
Create Date: 2025-02-10 07:10:24.960119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ff49eefe23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('truck',
    sa.Column('fuel_type', sa.Enum('DIESEL', 'LPG', name='fueltype', native_enum=False), nullable=False),
    sa.Column('truck_brand', sa.Enum('SCANIA', 'MERCEDES', 'VOLVO', name='truckbrand', native_enum=False), nullable=False),
    sa.Column('truck_id', sa.Uuid(), nullable=False),
    sa.Column('number_plate', sa.String(length=60), nullable=False),
    sa.Column('distance_driven', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('truck_id'),
    sa.UniqueConstraint('number_plate')
    )
    op.create_table('driver',
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('truck_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['truck_id'], ['truck.truck_id'], ),
    sa.PrimaryKeyConstraint('driver_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('truck_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver')
    op.drop_table('truck')
    # ### end Alembic commands ###
